# Generated by Django 5.2.7 on 2025-10-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('influencer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('contact_email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
