# Generated by Django 5.2.7 on 2025-10-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
