# Generated by Django 5.2.7 on 2025-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_influencerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
