# Generated by Django 5.2.7 on 2025-10-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_influencerprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerprofile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
